spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.157.129:3307/test-oauth?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: 123456
  session:
    store-type: none
  redis:
    host: 192.168.157.129
    port: 6379
logging:
  config: classpath:logback.xml
server:
  port: 8081

#oauth2配置
security:
  oauth2:
    token:
      store:
        type: jwt
#      clientId: wxy
#      clientSecret: wxysecret
#      registered-redirect-uri: http://example.com

wxy:
  security:
    browser:
#      loginPage: /demo-login.html
      loginType: JSON

